
/configure/registrarRoles:
  post:
    tags:
      - Roles
    security: []
    description: Registrar tipo Documentos
    requestBody:
      content:
        application/json:
          schema:
             $ref: '#/components/schemas/roles'            
    responses:
      200:
        description: Petición exitosa
        content:
          application/json:
            schema:
              type: object
              properties:
                roles:
                  type: object
                  properties:
                    name:
                      type: string
                    state:
                      type: boolean
                    created_at:
                      type: string
                    updated_at:
                      type: string
                    id_doctype: 
                      type: number
                msj:
                  type: string
                  description: Mensaje de respuesta 
            example:
              {
                  "tiporol": {
                      "name": "Estudiante",
                      "state": true,
                      "created_at": "2023-03-21T20:15:40.523-05:00",
                      "updated_at": "2023-03-21T20:15:40.524-05:00",
                      "id_roles": 14
                  },
                  "msj": "Tipo Rol registrado"
              }
